"""
Execute Embeddings
Script to demonstrate embeddings generation functionality.
"""

from base_cookbook import BaseCookbook
from src.rag.generate_embeddings import generate_embeddings


class EmbeddingsCookbook(BaseCookbook):
    """Cookbook for embeddings generation."""

    def __init__(self):
        super().__init__("EMBEDDINGS GENERATION")

    def run(self):
        # Path to the chunks file (generated by execute_generate_chunks.py)
        chunks_path = self.output_dir / "sample_chunks.txt"

        self.print_header(f"Processing file: {chunks_path.name}")

        # Step 1: Read chunks from file
        print("\n📄 Step 1: Reading chunks from file...")
        chunks_content = self.read_file(chunks_path)

        # Parse chunks from the saved format
        chunks = []
        current_chunk = []
        for line in chunks_content.split("\n"):
            if line.startswith("=" * 80):
                if current_chunk:
                    # Join and add the previous chunk (skip the CHUNK N line)
                    chunk_text = "\n".join(current_chunk[1:]).strip()
                    if chunk_text:
                        chunks.append(chunk_text)
                    current_chunk = []
            elif line.startswith("CHUNK "):
                current_chunk = [line]
            elif current_chunk:
                current_chunk.append(line)

        # Add the last chunk if exists
        if current_chunk:
            chunk_text = "\n".join(current_chunk[1:]).strip()
            if chunk_text:
                chunks.append(chunk_text)

        print(f"  ✓ Loaded {len(chunks)} chunks")

        # Step 2: Generate embeddings
        print("\n🧮 Step 2: Generating embeddings...")
        print(f"  Processing {len(chunks)} chunks...")
        embeddings = generate_embeddings(
            chunks=chunks,
        )
        print(f"  ✓ Generated {len(embeddings)} embeddings")
        print(f"  ✓ Embedding dimension: {len(embeddings[0])}")

        # Display sample embedding
        print("\n🔢 Sample embedding (first 10 dimensions of first chunk):")
        print(f"  {embeddings[0][:10]}...")

        # Save embeddings as JSON
        embeddings_data = {
            "chunk_count": len(chunks),
            "embedding_dimension": len(embeddings[0]),
            "embeddings": embeddings,
        }
        embeddings_path = self.save_json_file(embeddings_data, "sample_embeddings.json")

        print("\n" + "=" * 80)
        print("✅ Successfully generated embeddings!")
        print(f"📁 Embeddings saved to: {embeddings_path}")
        print("=" * 80)


if __name__ == "__main__":
    cookbook = EmbeddingsCookbook()
    cookbook.execute()
