"""
Execute Embeddings
Script to demonstrate embeddings generation functionality.
"""

import asyncio
from base_cookbook import BaseCookbook
from src.process_document.generate_embeddings import generate_embeddings


class EmbeddingsCookbook(BaseCookbook):
    """Cookbook for embeddings generation."""

    def __init__(self):
        super().__init__("EMBEDDINGS GENERATION")

    async def run_async(self):
        # Path to the chunks file (generated by execute_generate_chunks.py)
        chunks_path = self.data_dir / "sample_chunks.txt"

        self.print_header(f"Processing file: {chunks_path.name}")

        # Step 1: Read chunks from file
        print("\n📄 Step 1: Reading chunks from file...")
        chunks_content = self.read_file(chunks_path)

        # Parse chunks from the saved format
        chunks = []
        lines = chunks_content.split("\n")
        i = 0
        while i < len(lines):
            line = lines[i]
            if line.startswith("=" * 80):
                # Check if next line is a CHUNK header
                if i + 1 < len(lines) and lines[i + 1].startswith("CHUNK "):
                    # Skip the === and CHUNK lines and the next === line
                    i += 3  # Skip ===, CHUNK N, ===
                    # Accumulate content until next ===
                    chunk_lines = []
                    while i < len(lines) and not lines[i].startswith("=" * 80):
                        chunk_lines.append(lines[i])
                        i += 1
                    chunk_text = "\n".join(chunk_lines).strip()
                    if chunk_text:
                        chunks.append(chunk_text)
                    # Don't increment i, we're already at the next ===
                    continue
            i += 1

        print(f"  ✓ Loaded {len(chunks)} chunks")

        # Step 2: Generate embeddings
        print("\n🧮 Step 2: Generating embeddings...")
        print(f"  Processing {len(chunks)} chunks...")
        embeddings, usage = await generate_embeddings(
            chunks=chunks,
        )
        print(f"  ✓ Generated {len(embeddings)} embeddings")
        print(f"  ✓ Embedding dimension: {len(embeddings[0])}")
        print(f"  ✓ Input tokens: {usage['input_tokens']:,}")
        print(f"  ✓ Cost: ${usage['cost']:.6f}")
        print(f"  ✓ Model: {usage['model']}")

        # Display sample embedding
        print("\n🔢 Sample embedding (first 10 dimensions of first chunk):")
        print(f"  {embeddings[0][:10]}...")

        # Save embeddings as JSON
        embeddings_data = {
            "chunk_count": len(chunks),
            "embedding_dimension": len(embeddings[0]),
            "embeddings": embeddings,
        }
        embeddings_path = self.save_json_file(embeddings_data, "sample_embeddings.json")

        print("\n" + "=" * 80)
        print("✅ Successfully generated embeddings!")
        print(f"📁 Embeddings saved to: {embeddings_path}")
        print("=" * 80)

    def run(self):
        """Synchronous wrapper for async run method."""
        asyncio.run(self.run_async())


if __name__ == "__main__":
    cookbook = EmbeddingsCookbook()
    cookbook.execute()
